language: java

before_script:
    - export MAVEN_OPTS="-Xmx2g"

notifications:

    email: false

    irc:
        channels:
            - 'ircnet.eversible.com#kesapojat-ci'
        on_success: change
        use_notice: true
        skip_join: true
        template:
            - '**'
            - '%{message}'
            - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}'
            - 'Build details : %{build_url}'
            - '**'

after_success:
    - mvn clean cobertura:cobertura coveralls:cobertura

